# Site
repository: violetbeach/violetbeach.github.io

# Personal info
name: 이재헌
title: Java Spring 서버 엔지니어
email: ti6419@gmail.com
website: https://jaehoney.tistory.com

# Additional icon links
additional_links:
  - title: Tech Blog
    icon: fab fa-blogger
    url: https://jaehoney.tistory.com

# Social links
github_username: violetbeach

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring 기반의 2년차 백엔드 개발자로 MAU 60만 그룹웨어 서비스의 **서버 개발** 및 **서비스 유지보수**를 해왔습니다. \
  <br>
  **좋은 코드**와 **테스트 코드**, 트래픽 증가를 충분히 고려한 **시스템 설계**로 인한 <mark>사용자 경험(UX)</mark> 향상을 목표합니다. \
  <br>
  성능 개선 시 **Worst Case**를 고려하고 메모리 누수 해결, SQL 튜닝, 트랜잭션 범위 개선 등을 했습니다. \
  <br>
  최근에는 동시성 문제와 이벤트 기반 아키텍처의 최종적 일관성에도 관심이 많습니다. \
  <br>
  **Blog**: <a href="https://jaehoney.tistory.com" target="_blank">https://jaehoney.tistory.com</a> <br>
  **Github**: <a href="https://github.com/violetbeach" target="_blank">https://github.com/violetbeach</a>

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag