# Site
repository: violetbeach/violetbeach.github.io

# Personal info
name: 이재헌
title: Java Spring 서버 엔지니어
email: ti6419@gmail.com
website: https://jaehoney.tistory.com

# Additional icon links
additional_links:
  - title: Tech Blog
    icon: fab fa-blogger
    url: https://jaehoney.tistory.com

# Social links
github_username: violetbeach

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring 기반의 1년차 백엔드 개발자로 MAU 60만 그룹웨어 서비스의 **API 개발**과 **서비스 유지보수**를 해왔습니다. 아침 공부를 좋아해서 **매일 1시간 30분 ~ 2시간 전에 출근**해서 블로그 포스팅 및 개인 공부를 하고 있습니다. \
  <br>
  <mark>SOLID 원칙 준수</mark>와 <mark>테스트 코드 작성</mark>을 매우 중요하게 여깁니다. **높은 가독성**과 **변경 용이성**이 유도된다고 생각하기 때문입니다. \
  트래픽 증가에 따른 시스템 확장에 대응할 수 있는 <mark>시스템 설계</mark>도 매우 중요하게 여깁니다.  

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag