# Site
repository: violetbeach/violetbeach.github.io

# Personal info
name: 이재헌
title: Java Spring 서버 엔지니어
email: ti6419@gmail.com
website: https://jaehoney.tistory.com

# Additional icon links
additional_links:
  - title: Tech Blog
    icon: fab fa-blogger
    url: https://jaehoney.tistory.com

# Social links
github_username: violetbeach

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring 기반의 2년차 백엔드 개발자로 MAU 60만 그룹웨어 서비스의 **서버 개발** 및 **서비스 유지보수**를 해왔습니다. \
  <br>
  <mark>SOLID 원칙</mark>을 충분히 준수하는 것을 선호하며, 좋은 유지보수성을 가진 코드와 \
  트래픽 증가를 충분히 고려한 <mark>시스템 설계</mark>로 인한 <mark>사용자 경험(UX)</mark> 향상을 목표로합니다. \
  <br>
  성능 개선을 할 때는 **Worse-case**를 기준으로 더 나은 방법을 선호하고, 메모리 문제 개선, SQL 튜닝, 트랜잭션 범위 개선 등을 했습니다. \
  <br>
  최근에는 이벤트 기반 아키텍처와 최종적 일관성, 동시성 이슈 등에 관심을 가집니다.
  
  Blog: https://jaehoney.tistory.com, Github: https://github.com/violetbeach

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag